Models/Track.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace AspMusicStore.Models
{
    public class Track
    {
        public int TrackID { get; set; }
        [Required]
        public string TrackTitle { get; set; }
        public string? TrackLyrics { get; set; }
        public int? Duration { get; set; }
        [NotMapped]
        public double? TrackRating { get; set; }
        [NotMapped]
        public List<int>? SelectedMusicians { get; set; }

        //Navigation properties
        public ICollection<Album> Albums { get; set; }
        public ICollection<Musician> Musicians { get; set; }
    }
}

Controllers/StatisticsController.cs
using AspMusicStore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspMusicStore.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly MusicStoreContext _context;
        public StatisticsController(MusicStoreContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var musicStoreContext = _context.Albums
                .Include(a => a.Genre)
                .Include(a => a.Tracks)
                .ThenInclude(t => t.Musicians);

            return View(await musicStoreContext.ToListAsync());
        }

        public async Task<IActionResult> AlbumAnalyticsAsync()
        {
            RatingsController.CalculateRatings(_context);
            var musicStoreContext = _context.Albums;

            return View(await musicStoreContext.ToListAsync());
        }

        public async Task<IActionResult> TrackAnalyticsAsync()
        {
            var musicStoreContext = _context.Ratings
                .Include(r => r.Track)
                .ThenInclude(a => a.Albums);

            RatingsController.CalculateRatings(_context);

            return View(await musicStoreContext.ToListAsync());
        }


    }
}

Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspMusicStore.Data;
using AspMusicStore.Models;

namespace AspMusicStore.Controllers
{
    public class TracksController : Controller
    {
        private readonly MusicStoreContext _context;

        public TracksController(MusicStoreContext context)
        {
            _context = context;
        }

        // GET: Tracks
        public async Task<IActionResult> Index()
        {
              return View(await _context.Tracks.ToListAsync());
        }

        // GET: Tracks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tracks == null)
            {
                return NotFound();
            }

            var track = await _context.Tracks
                .Include(t => t.Musicians)
                .FirstOrDefaultAsync(m => m.TrackID == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        // GET: Tracks/Create
        public IActionResult Create()
        {
            ViewData["MusicianIDs"] = new MultiSelectList(_context.Musicians, "MusicianID", "MusicianName");
            return View();
        }

        // POST: Tracks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrackID,TrackTitle,TrackLyrics,Duration,MusicianID")] Track track, List<int> selectedMusicians)
        {
            ViewData["MusicianIDs"] = new MultiSelectList(_context.Musicians, "MusicianID", "MusicianName", track.SelectedMusicians);

            AddMusiciansToTrack(track, selectedMusicians);

            if (ModelState.IsValid)
            {
                Console.WriteLine("Valid Model");
                _context.Add(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(track);
        }

        // GET: Tracks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Tracks == null)
            {
                return NotFound();
            }

            var track = await _context.Tracks
                .Include(m => m.Musicians)
                .FirstOrDefaultAsync(i => i.TrackID == id);
            if (track == null)
            {
                return NotFound();
            }
            
            ViewData["MusicianIDs"] = new MultiSelectList(_context.Musicians, "MusicianID", "MusicianName", track.Musicians.Select(t => t.MusicianID).ToArray());

            return View(track);
        }

        // POST: Tracks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrackID,TrackTitle,TrackLyrics,Duration")] Track track, List<int> selectedMusicians)
        {
            if (id != track.TrackID)
            {
                return NotFound();
            }

            await DeleteMusiciansFromTrack(track);
            AddMusiciansToTrack(track, selectedMusicians);


            if (ModelState.IsValid)
            {
                try
                {
                    _context.ChangeTracker.Clear();
                    _context.Update(track);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrackExists(track.TrackID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(track);
        }

        // GET: Tracks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tracks == null)
            {
                return NotFound();
            }

            var track = await _context.Tracks
                .FirstOrDefaultAsync(m => m.TrackID == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        // POST: Tracks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tracks == null)
            {
                return Problem("Entity set 'MusicStoreContext.Tracks'  is null.");
            }
            var track = await _context.Tracks.FindAsync(id);
            if (track != null)
            {
                _context.Tracks.Remove(track);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrackExists(int id)
        {
          return _context.Tracks.Any(e => e.TrackID == id);
        }

        private void AddMusiciansToTrack (Track track, List<int> selectedMusicians)
        {
            if (selectedMusicians != null)
            {

                track.Musicians = new List<Musician>();

                foreach (var musician in selectedMusicians)
                {
                    track.Musicians.Add(_context.Musicians.FirstOrDefault(m => m.MusicianID == musician));
                    Console.WriteLine(musician);
                }
            }
            else
            {
                Console.WriteLine("no selected Musicians");
            }
        }


        private async Task DeleteMusiciansFromTrack (Track track)
        {
            var dbTrack = this._context.Tracks.Include(m => m.Musicians)
                .SingleOrDefault(t => t.TrackID == track.TrackID);

            if (dbTrack.Musicians != null) {
                dbTrack.Musicians.Clear();
                await _context.SaveChangesAsync();
            }
 
        }
    }
}

Views/Tracks/Create.cshtml
@model AspMusicStore.Models.Track

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Track</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TrackTitle" class="control-label"></label>
                <input asp-for="TrackTitle" class="form-control" />
                <span asp-validation-for="TrackTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrackLyrics" class="control-label"></label>
                <textarea asp-for="TrackLyrics" class="form-control" /></textarea>
                <span asp-validation-for="TrackLyrics" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Musicians" class="control-label"></label>
                <select asp-for="SelectedMusicians" class="form-control" asp-items="ViewBag.MusicianIDs" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tracks/Delete.cshtml
@model AspMusicStore.Models.Track

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackLyrics)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackLyrics)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TrackID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tracks/Details.cshtml
@model AspMusicStore.Models.Track

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackLyrics)
        </dt>
        <dd class = "col-sm-10">
            <textarea readonly>@Model.TrackLyrics</textarea>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Musicians)
        </dt>
        <dd class="col-sm-10">
            @foreach (var musician in Model.Musicians)
            {
                <text>@musician.MusicianName</text> <br />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TrackID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Tracks/Edit.cshtml
@model AspMusicStore.Models.Track

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Track</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TrackID" />
            <div class="form-group">
                <label asp-for="TrackTitle" class="control-label"></label>
                <input asp-for="TrackTitle" class="form-control" />
                <span asp-validation-for="TrackTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrackLyrics" class="control-label"></label>
                <textarea asp-for="TrackLyrics" class="form-control" />@Model.TrackLyrics</textarea>
                <span asp-validation-for="TrackLyrics" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Musicians" class="control-label"></label>
                <select asp-for="SelectedMusicians" class="form-control" asp-items="ViewBag.MusicianIDs" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tracks/Index.cshtml
@model IEnumerable<AspMusicStore.Models.Track>

@{
    ViewData["Title"] = "Tracks";
}

<h1>Tracks</h1>

<form asp-controller="Statistics" asp-action="TrackAnalytics"><button>Analytics</button></form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrackTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TrackTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TrackID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TrackID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TrackID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>